<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rnc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>Relax NG Compact</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>[=,&amp;|?*+\\]</string>
			<key>name</key>
			<string>constant.character.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#[^#].*$</string>
			<key>name</key>
			<string>comment.line.number-sign.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>##.*$</string>
			<key>name</key>
			<string>support.class.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstart\b</string>
			<key>name</key>
			<string>keyword.control.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(parent|externalRef|grammar|div|include|namespace|default|datatypes)\b</string>
			<key>name</key>
			<string>keyword.operator.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(list|mixed|notAllowed|text|token|empty)\b</string>
			<key>name</key>
			<string>storage.type.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(xsd\:(string|boolean|float|double|decimal|date(Time)?|duration|hexBinary|base64Binary|anyURI|ID(REF(S)?)?|ENTIT(Y|IES)|NOTATION|normalizedString|token|language|IDREFS|NMTOKEN(S)?|(Q|NC)?Name|integer|nonNegativeInteger|positiveInteger|nonPositiveInteger|negativeInteger|byte|int|long|short|unsignedByte|unsignedInt|unsignedLong|unsignedShort|time|gYearMonth|gYear|gMonthDay|gDay|gMonth))\b</string>
			<key>name</key>
			<string>storage.type.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z][a-zA-Z0-9_]*:[a-zA-Z][a-zA-Z0-9_]*)\b</string>
			<key>name</key>
			<string>entity.other.inherited-class.rnc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rnc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.rnc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(attribute)\s+([a-zA-Z][a-zA-Z_0-9]*)\s*\{</string>
			<key>name</key>
			<string>meta.declaration.attribute.rnc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rnc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.rnc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(element)\s+([a-zA-Z][a-zA-Z_0-9]*)\s*\{</string>
			<key>name</key>
			<string>meta.declaration.element.rnc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.rnc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rnc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.rnc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rnc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.quoted.triple.rnc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rnc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'''</string>
			<key>end</key>
			<string>'''</string>
			<key>name</key>
			<string>string.quoted.triple.rnc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rnc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.annotation.rnc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(\])</string>
			<key>name</key>
			<string>support.class.rnc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rnc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.rnc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z][a-zA-Z_0-9\.]*)\s*=</string>
			<key>name</key>
			<string>meta.grammar_production.rnc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\]})]</string>
			<key>name</key>
			<string>invalid.illegal.rnc</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.rnc</string>
	<key>uuid</key>
	<string>85F32571-780F-4AAC-BA70-C2229E0B1BDA</string>
</dict>
</plist>
